version: '3'
services:
  player:
    image: rtls_player
    command: node server.js
    user: node
    environment:
      - NODE_ENV=production
    ports:
      - "3100:3000"
    restart: unless-stopped
